markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 6
paginate_path: page/:num

blog:
    name:                                              程冬的博客
    description:                                       记录技术、生活、感悟
    title:                                               程冬的博客
    url:                                                 blog.8hour.me
    duoshuo:                                             51weekend
    tongji:                                              # 百度统计ID
    qiniu:                                               # 七牛云地址
author:
    name:                                                程冬
    email:                                               51weekend@gmail.com
    weibo:                                               http://www.weibo.com/chenng
    github:                                              https://github.com/51weekend
    logo:                                                # logo地址
    douban:
        name:                                            http://www.douban.com/people/chengdong/
        key:                                             05e41203492cf78911ac3609db86e69b