# Site settings
title: "程冬的博客"
description: "程冬的博客."
keywords: "分布式, 软件架构, java"
baseurl: ""
url: "http:////51weekend.github.io"
highlighter: pygments
paginate: 5
author:
    name: 程冬
    github: 51weekend
    email:
    gitcafe: Havee
    twitter:
    facebook:
    googleplus:
    weibo: chenng
atom_path: /atom.xml
rss_path: /rss.xml

# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]
permalink: /:categories/:year-:month/:title.html

# comment
comments:
    duoshuo:
        name: 51weekend                              # short name
        rcomments:
            num: 10
            avatar: 0
            time: 0
            title: 0
            admin: 0
            length: 26
# 网站统计
analytics:
    baidu:
        siteid:                             # 百度统计 js 代码后的字符串

# blogroll
blogroll: true
brlist:
    - text: "酷壳"
      url : http://coolshell.cn/
